# This is sample slide

# Site metadata (OGP, title, ...)
[meta]
title= "Sample Slide for tomlide"
og_url = "https://example.com/"
og_title = "Sample Slide for tomlide"
og_image = "https://example.com/example.v1.png"
og_image_width = "600"
og_image_height = "300"
og_image_description = "Simple slide generator, description maybe include < or >"
# twitter_card: summary | summary_large_image
twitter_card = "summary_large_image"
# twitter_creator: @<username>
twitter_creator = "@kaito_tateyama"
# twitter_image: cache by Twitter, change url when change twitter image.
twitter_image = "https://example.com/example.v1.png"
# icon: .png | .ico
icon = "https://example.com/example.png"

[[slide]]
title = "Sample Slide"
text = """
@kaito_tateyama
"""

[[slide]]
title = "First Page"
text = """
Hello, this is sample page for tomlide.
This is sample text. <>::<><><>::<!!
"""

[[slide]]
title = "Second Page"
text = """
Hello, this is sample page for tomlide.
This is sample text.
tomlide is simple toml-based slide generator.
"""

[[slide]]
title = "Link Page"
text = """
Hello, this is link page for tomlide.
This is simple usage @[link](https://github.com/uta8a/tomlide)
link alias usage: @[link: Project repository](https://github.com/uta8a/tomlide)
slide alias usage: @[link: slide 1](@1)
"""

[[slide]]
title = "Image Page"
text = """
Hello, this is image page for tomlide.
@[image](relative path)
@[image](web path)
@[image: alt and description](relative | web path)
"""

[[slide]]
title = "Emoji Page"
text = """
Hello, this is emoji page for tomlide.
@[:sob:]
@[:tada:]
"""

[[slide]]
title = "Bold Page"
text = """
Hello, this is Bold page for tomlide.
@[*THIS IS BOLD STYLE*]
"""

[[slide]]
title = "Thank you!"
text = "Any questions?"
